### ISSUE TITLE
BUG - Hamburger isnt working on about me page

### ISSUE THREAD

**Issue by fostyler** [AmandaWelt/resume#2]
1. Go to about me page
2. Click the hamburger menu
3. Notice menu does not open

**Comment by fostyler** [comment]
To get started

1. Open a terminal and change directories to your project `cd to/your/project`
2.  Check out the main branch `git checkout main`
3. Pull down the latest code change `git pull origin main`
4. Cut a new branch `git checkout -b 'bug/hamburger-not-working'`
5. Investigate the problem, make code changes that fix the problem
6. `git status` look at the files you've changed, specifics with `git diff`
7. if all looks good, its time to save your work.  `git add -A` and then `git commit -m 'some message'` (The message is a note about what you did)
8. git push origin bug/hamburger-not-working
9. go to github, open a pull request to merge your new branch in to main

**Comment by AmandaWelt** [comment]
i wasnt sure how to do step 5-6 so im pasting the results here "amandawelt@amandas-MacBook-Pro myportfolio % git status
On branch main
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   aboutme.html

no changes added to commit (use "git add" and/or "git commit -a")
amandawelt@amandas-MacBook-Pro myportfolio % git di
ff
diff --git a/aboutme.html b/aboutme.html
index 3589ed4..12f2da7 100644
--- a/aboutme.html
+++ b/aboutme.html
@@ -6,6 +6,7 @@
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <title>About Me - Amanda Welt</title>
     <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
+    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
     <style>
         body.about {
             background-color: black; /* Set black background */
@@ -36,7 +37,6 @@
             margin-bottom: 20px;
         }
 
-
         #menu-btn {
             position: absolute; /* Position the menu button */
             top: 20px; /* Adjust as needed */
@@ -60,6 +60,7 @@
diff --git a/aboutme.html b/aboutme.html
diff --git a/aboutme.html b/aboutme.html
index 3589ed4..12f2da7 100644
--- a/aboutme.html
+++ b/aboutme.html
@@ -6,6 +6,7 @@
     <meta name="viewport" content="width=device-wi
dth, initial-scale=1.0">
     <title>About Me - Amanda Welt</title>
     <link href="https://cdn.jsdelivr.net/npm/tailw
indcss@2.2.19/dist/tailwind.min.css" rel="styleshee
t">
+    <link rel="stylesheet" href="https://cdnjs.clo
udflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/
all.min.css">
diff --git a/aboutme.html b/aboutme.html
index 3589ed4..12f2da7 100644
--- a/aboutme.html
+++ b/aboutme.html
@@ -6,6 +6,7 @@
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <title>About Me - Amanda Welt</title>
     <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
+    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">"
